name: vprofile actions
on: workflow_dispatch
env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: vprofileapp
    EKS_CLUSTER: vprofile-eks
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: maven test
              run: mvn test

            - name: Check style
              run: mvn checkstyle:checkstyle
            
            # Set up Java 11 for the build and test steps
            - name: set java 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            
            ################################# setup sonar-scanner
            # - name: setup sonar-scanner
            #   uses: warchant/setup-sonar-scanner@v7
            # # Run sonar-scanner with the necessary parameters
            # - name: run sonar-scanner
            #   run: sonar-scanner
            #     -Dsonar.host.url=${{ secrets.SONAR_URL }}
            #     -Dsonar.login=${{ secrets.SONAR_TOKEN }}a
            #     -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            #     -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            #     -Dsonar.sources=src/
            #     -Dsonar.junit.reportsPath=target/surefire-reports/ 
            #     -Dsonar.jacoco.reportsPath=target/jacoco.exec 
            #     -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
            #     -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/  
            
            # # check the quality gate status
            # - name: SonarQube Quality Gate check
            #   id: sonarqube-quality-gate-check
            #   uses: sonarsource/sonarqube-quality-gate-action@master
            #     # Force to fail step after specific time.\
            #   timeout-minutes: 5
            #   env:
            #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #     SONAR_HOST_URL: ${{ secrets.SONAR_URL }} #OPTIONAL\
    build-and-publish:
        runs-on: ubuntu-latest
        needs: testing
        steps:
            - name: Checkout code
              uses: actions/checkout@v4


            - name: Build & Upload image to ECR
              uses: appleboy/docker-ecr-action@master
              with:
                access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                registry: ${{ secrets.REGISTRY }}
                repo: ${{ env.ECR_REPOSITORY }}
                region: ${{ env.AWS_REGION }}
                tags: latest,${{ github.run_number }}
                daemon_off: false
                dockerfile: ./Dockerfile
                context: ./
    deploy-to-eks:
        runs-on: ubuntu-latest
        needs: build-and-publish
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Update kubeconfig for EKS cluster
              run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

            - name: Create/Update regcred
              run: |
                kubectl create secret docker-registry regcred \
                --docker-server=${{ secrets.REGISTRY }} \
                --docker-username=AWS \
                --docker-password=$(aws ecr get-login-password --region ${{ env.AWS_REGION }}) \
                --dry-run=client -o yaml | kubectl apply -f -


            - name: Deploy Helm
              uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}
                cluster-name: ${{ env.EKS_CLUSTER }}
                #config-files: .github/values/dev.yaml\
                chart-path: helm/vprofilecharts
                namespace: default
                values: appimage=${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY }},apptag=${{ github.run_number }}
                name: vprofile-stack    